export const TOGGLE_INFO_ELEMENTS = 'TOGGLE_INFO_ELEMENTS';
export const TOGGLE_CHART_ELEMENTS = 'TOGGLE_CHART_ELEMENTS';
export const TOGGLE_KANAL_ELEMENTS = 'TOGGLE_KANAL_ELEMENTS';
export const TOGGLE_FILTER_ELEMENT = 'TOGGLE_FILTER_ELEMENT';
export const TOGGLE_DETAIL_ELEMENTS = 'TOGGLE_DETAIL_ELEMENTS';
export const SEARCH_BY_POINT = 'SEARCH_BY_POINT';
export const SEARCH_BY_KASSENZEICHEN = 'SEARCH_BY_KASSENZEICHEN';
export const CHANGE_LAYER_OPACITY = 'CHANGE_LAYER_OPACITY';
export const CHANGE_LAYER_ENABLED = 'CHANGE_LAYER_ENABLED';
export const SHOW_SETTINGS = 'SHOW_SETTINGS';

